package(default_visibility = ["//visibility:public"])

exports_files([
    "MODULE.bazel",
    "cargo-bazel-lock.json",
    "examples/clevr/data.shf",
    "examples/clevr/model.shf",
    "examples/clevr/utils.shf",
    "examples/hydra/hydra.shf",
    "examples/mlp/mlp.shf",
    "examples/mlp/training.shf",
    "examples/nanoGPT/model.shf",
    "examples/nanoGPT/train.shf",
])
